name: PR Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited]

permissions:
  contents: read

jobs:
  check:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: echo "${{ github.event.pull_request.title }}" | npx commitlint
