name: Publish

on:
  push:
    tags:
      - v*.*.*

concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

env:
  NX_NON_NATIVE_HASHER: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm run release
